# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'outages', '0001_initial'), (b'outages', '0002_outages_outagetype'), (b'outages', '0003_auto_20170417_1523')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('OutageID', models.IntegerField()),
                ('ResourceID', models.CharField(max_length=64)),
                ('WebURL', models.CharField(max_length=320)),
                ('Subject', models.CharField(db_index=True, max_length=120)),
                ('Content', models.CharField(db_index=True, max_length=1536)),
                ('OutageStart', models.DateTimeField(null=True)),
                ('OutageEnd', models.DateTimeField(null=True)),
                ('SiteID', models.CharField(db_index=True, max_length=40)),
                ('OutageType', models.CharField(default='Full', max_length=16)),
                ('ID', models.CharField(default='1234:asdfasdfsa', max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_name': 'xcsr',
            },
        ),
    ]
