# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('OutageID', models.IntegerField(primary_key=True, serialize=False)),
                ('ResourceID', models.CharField(max_length=64)),
                ('WebURL', models.CharField(max_length=320)),
                ('Subject', models.CharField(db_index=True, max_length=120)),
                ('Content', models.CharField(db_index=True, max_length=1536)),
                ('OutageStart', models.DateTimeField(null=True)),
                ('OutageEnd', models.DateTimeField(null=True)),
                ('SiteID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'db_name': 'xcsr',
            },
        ),
    ]
