# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outages',
            fields=[
                ('ID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('OutageID', models.IntegerField()),
                ('ResourceID', models.CharField(max_length=64)),
                ('WebURL', models.CharField(max_length=320)),
                ('Subject', models.CharField(db_index=True, max_length=120)),
                ('Content', models.CharField(db_index=True, max_length=1536)),
                ('OutageStart', models.DateTimeField(null=True)),
                ('OutageEnd', models.DateTimeField(null=True)),
                ('SiteID', models.CharField(db_index=True, max_length=40)),
                ('OutageType', models.CharField(max_length=16)),
            ],
            options={
                'db_name': 'xcsr',
            },

        ),
    ]
