# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_squashed_0003_auto_20170417_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outages',
            name='ID',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outages',
            name='OutageType',
            field=models.CharField(max_length=16),
        ),
    ]
