# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-17 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outages',
            name='Content',
            field=models.CharField(db_index=True, max_length=4000),
        ),
    ]
