# Generated by Django 2.2.24 on 2022-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0002_auto_20190317_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outages',
            name='Content',
            field=models.CharField(db_index=True, max_length=8000),
        ),
    ]
