# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdcdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSEDELocalUsermap',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField()),
                ('portal_login', models.CharField(db_index=True, max_length=30)),
                ('resource_id', models.IntegerField()),
                ('resource_name', models.CharField(max_length=200)),
                ('local_username', models.CharField(max_length=30)),
                ('ResourceID', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'db_name': 'xcsr',
            },
        ),
        migrations.AlterUniqueTogether(
            name='xsedelocalusermap',
            unique_together=set([('resource_id', 'local_username')]),
        ),
    ]
