# Generated by Django 2.2.18 on 2021-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdcdb', '0004_xsedefos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgresource',
            name='ResourceID',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
