# Generated by Django 2.2.24 on 2022-02-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdcdb', '0005_auto_20210702_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsedelocalusermap',
            name='ResourceID',
            field=models.CharField(max_length=40),
        ),
    ]
