# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Exchange', models.CharField(max_length=255)),
                ('RoutingKey', models.CharField(db_index=True, max_length=255)),
                ('ProcessingNode', models.CharField(max_length=64)),
                ('ProcessingApp', models.CharField(db_index=True, max_length=64)),
                ('ErrorTime', models.DateTimeField(db_index=True)),
                ('ErrorCode', models.CharField(max_length=64)),
                ('ErrorMessage', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'db_name': 'xcsr',
            },
        ),
        migrations.CreateModel(
            name='ProcessingRecord',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Topic', models.CharField(db_index=True, max_length=255)),
                ('About', models.CharField(db_index=True, max_length=255)),
                ('ProcessingNode', models.CharField(max_length=64)),
                ('ProcessingApp', models.CharField(max_length=64)),
                ('ProcessingStart', models.DateTimeField()),
                ('ProcessingEnd', models.DateTimeField()),
                ('ProcessingCode', models.CharField(max_length=64, null=True)),
                ('ProcessingMessage', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'db_name': 'xcsr',
            },
        ),
    ]
