# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingerror',
            name='Reference1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
