# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_status', '0004_auto_20170123_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingerror',
            old_name='RoutingKey',
            new_name='About',
        ),
        migrations.RemoveField(
            model_name='processingerror',
            name='Exchange',
        ),
        migrations.AddField(
            model_name='processingerror',
            name='Topic',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
