# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 21:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_status', '0005_auto_20170131_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherInfo',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('Type', models.CharField(max_length=32)),
                ('Version', models.CharField(max_length=32)),
                ('Hostname', models.CharField(max_length=64)),
                ('Location', models.CharField(max_length=64, null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('CreationTime', models.DateTimeField()),
                ('RecentHistory', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
                'db_name': 'xcsr',
            },
        ),
    ]
