# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr_db', '0002_auto_20160715_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdrresource',
            name='other_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='rdrresource',
            name='parent_resource',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdrresource',
            name='resource_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
