# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr_db', '0003_auto_20160720_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdrresource',
            name='project_affiliation',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='rdrresource',
            name='provider_level',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
