# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr_db', '0004_auto_20170203_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdrresource',
            name='latest_status',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
