# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdr_db', '0005_rdrresource_latest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdrresource',
            name='latest_status_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rdrresource',
            name='latest_status_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rdrresource',
            name='latest_status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
