drop table django_migrations ;
drop table outages_outages ;
drop table processing_status_processingerror ;
drop table processing_status_processingrecord ;
drop table projectresources_projectresource ;
drop table rdr_db_rdrresource ;
drop table speedpage_speedpage ;
drop table xcsr_db_componentsprequirement ;
drop table xdcdb_tgresource ;
