drop table auth_group_permissions ;
drop table auth_user_user_permissions ;
drop table auth_permission ;
drop table auth_user_groups ;
drop table django_admin_log ;
drop table django_content_type ;
drop table django_migrations ;
drop table django_session ;
drop table django.social_auth_usersocialauth;
drop table social_auth_partial;
drop table social_auth_nonce;
drop table social_auth_code;
drop table social_auth_association;
drop table auth_group ;
drop table auth_user ;
