# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 14:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('ProviderID', models.CharField(max_length=200, null=True)),
                ('Type', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=8000, null=True)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
                ('LocalID', models.CharField(db_index=True, max_length=32, null=True)),
                ('Keywords', models.CharField(max_length=1000, null=True)),
                ('Associations', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceProvider',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('LocalID', models.CharField(db_index=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
    ]
