# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Description',
            field=models.CharField(max_length=24000, null=True),
        ),
    ]
