# Generated by Django 2.2.9 on 2020-03-17 22:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceV3',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Affiliation', models.CharField(max_length=32)),
                ('LocalID', models.CharField(max_length=64, null=True)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
                ('Name', models.CharField(max_length=255)),
                ('ResourceGroup', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=64)),
                ('ShortDescription', models.CharField(max_length=1200, null=True)),
                ('ProviderID', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=24000, null=True)),
                ('Topics', models.CharField(max_length=1000, null=True)),
                ('Keywords', models.CharField(max_length=1000, null=True)),
                ('Audience', models.CharField(max_length=200, null=True)),
                ('StartDateTime', models.DateTimeField(null=True)),
                ('EndDateTime', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV3Catalog',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=255)),
                ('Affiliation', models.CharField(max_length=32)),
                ('ShortDescription', models.CharField(max_length=1000)),
                ('CatalogMetaURL', models.URLField(blank=True)),
                ('CatalogUserURL', models.URLField(blank=True)),
                ('CatalogAPIURL', models.URLField(blank=True)),
                ('CatalogSchemaURL', models.URLField(blank=True)),
            ],
            options={
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV3Local',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('LocalID', models.CharField(db_index=True, max_length=64, null=True)),
                ('LocalType', models.CharField(max_length=32, null=True)),
                ('LocalURL', models.CharField(max_length=200, null=True)),
                ('CatalogMetaURL', models.CharField(max_length=200, null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV3Relation',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('FirstResourceID', models.CharField(db_index=True, max_length=200)),
                ('SecondResourceID', models.CharField(db_index=True, max_length=200)),
                ('RelationType', models.CharField(max_length=32)),
            ],
            options={
                'db_name': 'glue2',
            },
        ),
    ]
