# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-06 17:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceV2',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('ProviderID', models.CharField(max_length=200, null=True)),
                ('ResourceGroup', models.CharField(max_length=64, null=True)),
                ('Type', models.CharField(max_length=32)),
                ('ShortDescription', models.CharField(max_length=500, null=True)),
                ('Description', models.CharField(max_length=24000, null=True)),
                ('QualityLevel', models.CharField(max_length=16, null=True)),
                ('LocalID', models.CharField(db_index=True, max_length=200, null=True)),
                ('Topics', models.CharField(max_length=1000, null=True)),
                ('Keywords', models.CharField(max_length=1000, null=True)),
                ('Associations', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV2Guide',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('LocalID', models.CharField(db_index=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV2GuideResource',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CuratedGuideID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_v2.ResourceV2Guide')),
                ('ResourceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_v2.ResourceV2')),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ResourceV2Provider',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Affiliation', models.CharField(db_index=True, max_length=32)),
                ('LocalID', models.CharField(db_index=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
    ]
