# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcev2guideresource',
            name='CuratedGuideID',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcev2guideresource',
            name='ResourceID',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
