# Generated by Django 2.2.9 on 2020-02-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_v2', '0002_auto_20190807_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcev2',
            name='ShortDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
