# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='EntityJSON',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
