# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_db', '0002_auto_20160718_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
