# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_db', '0003_auto_20170106_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='ErrorMessage',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
