# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_db', '0004_auto_20170110_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Validity',
            field=models.DurationField(null=True),
        ),
    ]
