# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue2_db', '0003_auto_20160718_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractservice',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationenvironment',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationhandle',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computingactivity',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computingmanager',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computingshare',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executionenvironment',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
