# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 13:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue2_db', '0005_auto_20171027_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceleratorEnvironment',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('Type', models.CharField(max_length=16, null=True)),
                ('Vendor', models.CharField(max_length=32, null=True)),
                ('Model', models.CharField(max_length=32, null=True)),
                ('Version', models.CharField(max_length=16, null=True)),
                ('PhysicalAccelerators', models.IntegerField(null=True)),
                ('LogicalAccelerators', models.IntegerField(null=True)),
                ('ComputeCapacity', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ComputingManagerAcceleratorInfo',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('TotalPhysicalAccelerators', models.IntegerField(null=True)),
                ('TotalAcceleratorsSlots', models.IntegerField(null=True)),
                ('UsedAcceleratorSlots', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
        migrations.CreateModel(
            name='ComputingShareAcceleratorInfo',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('CreationTime', models.DateTimeField()),
                ('Validity', models.DurationField(null=True)),
                ('EntityJSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
                ('FreeAcceleratorSlots', models.IntegerField(null=True)),
                ('UsedAcceleratorSlots', models.IntegerField(null=True)),
                ('MaxAcceleratorSlotsPerJob', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'db_name': 'glue2',
            },
        ),
    ]
