# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue2_db', '0009_admindomain_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='Rule',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='Scheme',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userdomain',
            name='Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdomain',
            name='Member',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userdomain',
            name='UserManager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
