# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(db_index=True, max_length=32)),
                ('ResourceID', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'db_name': 'xcsr',
            },
        ),
    ]
